#xiaoqiang:
#  client:
#    classloader: true
#    cpu: true
#    gc: false
#    memory: true
#    runtime: true
#    thread: true
#    retryCount: 3
#    retryDelay: 500

xiaoqiang:
  monitor:
    classloader: true
    cpu: true
    gc: true
    memory: true
    runtime: true
    thread: true
  retry:
    Count: 3
    Delay: 500
    onlyMyPackage: false
  xiaoQiangURL: localhost:5140
  instanceName: xiaoqTest

