spring:
  profiles:
    active:  peer0
xiaoqiang:
  monitor:
    clazz: true
    cpu: true
    gc: true
    memory: true
    runtime: true
    thread: true
  retry:
    Count: 3
    Delay: 500
    onlyMyPackage: false
---
xiaoqiang:
  xiaoQiangServerURL: localhost:5140
  instanceName: test0
server:
  port: 8080
spring:
  profiles: peer0
---
xiaoqiang:
  xiaoQiangServerURL: localhost:5140
  instanceName: test01
server:
  port: 8081
spring:
  profiles: peer1


