xiaoqiang:
  xiaoQiangServerURL: localhost:5140
  instanceName: xiaoqTest
  monitor:
    clazz: true
    cpu: true
    gc: true
    memory: true
    runtime: true
    thread: true
  retry:
    Count: 3
    Delay: 500
    onlyMyPackage: false


